import type {
  Accessory,
  AvatarCategory,
  AvatarKind,
  BgTone,
  ClothColor,
  FaceExtra,
  HairColor,
  HairStyle,
  Outfit,
  SkinTone,
} from "./tokens";

export type MascotId = "panda" | "fox" | "owl" | "cat" | "penguin" | "bear";

export type AvatarDefinition = {
  id: string;
  label: string;
  category: AvatarCategory;
  kind: AvatarKind;
  /** Legacy public SVG path when available */
  src?: string;
  bg?: BgTone;
  skin?: SkinTone;
  hair?: HairColor;
  hairStyle?: HairStyle;
  cloth?: ClothColor;
  outfit?: Outfit;
  accessory?: Accessory;
  face?: FaceExtra;
  age?: "adult" | "youth";
  robotColor?: string;
  mascot?: MascotId;
  initials?: string;
  gradientFrom?: string;
  gradientTo?: string;
};

/**
 * Production avatar registry — add entries here without changing Avatar.tsx.
 * IDs must stay ≤40 chars (DB / API constraint). Legacy man/woman/boy/girl kept.
 */
export const AVATAR_MAP: Record<string, AvatarDefinition> = {
  // —— Legacy (existing profiles) ——
  "man-1": {
    id: "man-1",
    label: "Alex",
    category: "man",
    kind: "human",
    src: "/avatars/man-1.svg",
    bg: "sky",
    skin: "light",
    hair: "darkBrown",
    hairStyle: "short",
    cloth: "navy",
    outfit: "blazer",
  },
  "man-2": {
    id: "man-2",
    label: "Jordan",
    category: "man",
    kind: "human",
    src: "/avatars/man-2.svg",
    bg: "mint",
    skin: "tan",
    hair: "black",
    hairStyle: "side",
    cloth: "forest",
    outfit: "shirt",
    face: "mustache",
  },
  "man-3": {
    id: "man-3",
    label: "Sam",
    category: "man",
    kind: "human",
    src: "/avatars/man-3.svg",
    bg: "sand",
    skin: "fair",
    hair: "brown",
    hairStyle: "short",
    cloth: "brown",
    outfit: "sweater",
    face: "beard",
  },
  "man-4": {
    id: "man-4",
    label: "Chris",
    category: "man",
    kind: "human",
    src: "/avatars/man-4.svg",
    bg: "lavender",
    skin: "brown",
    hair: "black",
    hairStyle: "side",
    cloth: "purple",
    outfit: "blazer",
    face: "blush",
  },
  "woman-1": {
    id: "woman-1",
    label: "Ava",
    category: "woman",
    kind: "human",
    src: "/avatars/woman-1.svg",
    bg: "blush",
    skin: "fair",
    hair: "auburn",
    hairStyle: "long",
    cloth: "magenta",
    outfit: "blazer",
    face: "blush",
  },
  "woman-2": {
    id: "woman-2",
    label: "Maya",
    category: "woman",
    kind: "human",
    src: "/avatars/woman-2.svg",
    bg: "lime",
    skin: "medium",
    hair: "blonde",
    hairStyle: "long",
    cloth: "green",
    outfit: "shirt",
    face: "blush",
  },
  "woman-3": {
    id: "woman-3",
    label: "Nina",
    category: "woman",
    kind: "human",
    src: "/avatars/woman-3.svg",
    bg: "navy",
    skin: "tan",
    hair: "black",
    hairStyle: "bob",
    cloth: "blue",
    outfit: "blazer",
  },
  "woman-4": {
    id: "woman-4",
    label: "Priya",
    category: "woman",
    kind: "human",
    src: "/avatars/woman-4.svg",
    bg: "peach",
    skin: "brown",
    hair: "darkBrown",
    hairStyle: "long",
    cloth: "orange",
    outfit: "sweater",
    face: "blush",
  },
  "boy-1": {
    id: "boy-1",
    label: "Leo",
    category: "boy",
    kind: "human",
    src: "/avatars/boy-1.svg",
    bg: "ice",
    skin: "fair",
    hair: "brown",
    hairStyle: "short",
    cloth: "sky",
    outfit: "tee",
    age: "youth",
    face: "blush",
  },
  "boy-2": {
    id: "boy-2",
    label: "Max",
    category: "boy",
    kind: "human",
    src: "/avatars/boy-2.svg",
    bg: "cream",
    skin: "tan",
    hair: "black",
    hairStyle: "side",
    cloth: "amber",
    outfit: "tee",
    age: "youth",
  },
  "boy-3": {
    id: "boy-3",
    label: "Kai",
    category: "boy",
    kind: "human",
    src: "/avatars/boy-3.svg",
    bg: "lime",
    skin: "light",
    hair: "darkBrown",
    hairStyle: "short",
    cloth: "leaf",
    outfit: "hoodie",
    age: "youth",
  },
  "boy-4": {
    id: "boy-4",
    label: "Omar",
    category: "boy",
    kind: "human",
    src: "/avatars/boy-4.svg",
    bg: "rose",
    skin: "brown",
    hair: "black",
    hairStyle: "short",
    cloth: "violet",
    outfit: "tee",
    age: "youth",
    face: "blush",
  },
  "girl-1": {
    id: "girl-1",
    label: "Mia",
    category: "girl",
    kind: "human",
    src: "/avatars/girl-1.svg",
    bg: "blush",
    skin: "fair",
    hair: "auburn",
    hairStyle: "long",
    cloth: "pink",
    outfit: "tee",
    age: "youth",
    face: "blush",
  },
  "girl-2": {
    id: "girl-2",
    label: "Zoe",
    category: "girl",
    kind: "human",
    src: "/avatars/girl-2.svg",
    bg: "lilac",
    skin: "medium",
    hair: "lightBlonde",
    hairStyle: "long",
    cloth: "indigo",
    outfit: "sweater",
    age: "youth",
    face: "blush",
  },
  "girl-3": {
    id: "girl-3",
    label: "Ivy",
    category: "girl",
    kind: "human",
    src: "/avatars/girl-3.svg",
    bg: "teal",
    skin: "tan",
    hair: "black",
    hairStyle: "long",
    cloth: "teal",
    outfit: "tee",
    age: "youth",
    face: "blush",
  },
  "girl-4": {
    id: "girl-4",
    label: "Noor",
    category: "girl",
    kind: "human",
    src: "/avatars/girl-4.svg",
    bg: "peach",
    skin: "brown",
    hair: "darkBrown",
    hairStyle: "curly",
    cloth: "tangerine",
    outfit: "hoodie",
    age: "youth",
    face: "blush",
  },

  // —— Professional ——
  "pro-male-01": {
    id: "pro-male-01",
    label: "Business",
    category: "professional",
    kind: "human",
    bg: "sky",
    skin: "medium",
    hair: "black",
    hairStyle: "side",
    cloth: "navy",
    outfit: "tie",
  },
  "pro-female-01": {
    id: "pro-female-01",
    label: "Executive",
    category: "professional",
    kind: "human",
    bg: "lilac",
    skin: "fair",
    hair: "brown",
    hairStyle: "bob",
    cloth: "charcoal",
    outfit: "blazer",
  },
  "pro-manager": {
    id: "pro-manager",
    label: "Manager",
    category: "professional",
    kind: "human",
    bg: "sand",
    skin: "tan",
    hair: "gray",
    hairStyle: "short",
    cloth: "steel",
    outfit: "blazer",
    face: "beard",
  },
  "pro-consultant": {
    id: "pro-consultant",
    label: "Consultant",
    category: "professional",
    kind: "human",
    bg: "mint",
    skin: "light",
    hair: "darkBrown",
    hairStyle: "bun",
    cloth: "forest",
    outfit: "blazer",
    accessory: "glasses",
  },
  "pro-hr": {
    id: "pro-hr",
    label: "People Ops",
    category: "professional",
    kind: "human",
    bg: "blush",
    skin: "medium",
    hair: "auburn",
    hairStyle: "ponytail",
    cloth: "magenta",
    outfit: "shirt",
    face: "blush",
  },
  "pro-finance": {
    id: "pro-finance",
    label: "Finance",
    category: "professional",
    kind: "human",
    bg: "cream",
    skin: "brown",
    hair: "black",
    hairStyle: "short",
    cloth: "navy",
    outfit: "tie",
    accessory: "glasses",
  },
  "pro-legal": {
    id: "pro-legal",
    label: "Legal",
    category: "professional",
    kind: "human",
    bg: "slate",
    skin: "deep",
    hair: "black",
    hairStyle: "side",
    cloth: "charcoal",
    outfit: "blazer",
  },
  "pro-sales": {
    id: "pro-sales",
    label: "Sales",
    category: "professional",
    kind: "human",
    bg: "peach",
    skin: "fair",
    hair: "blonde",
    hairStyle: "bob",
    cloth: "crimson",
    outfit: "blazer",
    face: "blush",
  },
  "pro-support": {
    id: "pro-support",
    label: "Support",
    category: "professional",
    kind: "human",
    bg: "ice",
    skin: "tan",
    hair: "brown",
    hairStyle: "short",
    cloth: "sky",
    outfit: "polo",
    accessory: "headset",
  },
  "pro-hijab": {
    id: "pro-hijab",
    label: "Consultant",
    category: "professional",
    kind: "human",
    bg: "teal",
    skin: "medium",
    hair: "teal",
    hairStyle: "hijab",
    cloth: "teal",
    outfit: "blazer",
  },

  // —— Casual ——
  "cas-hoodie": {
    id: "cas-hoodie",
    label: "Hoodie",
    category: "casual",
    kind: "human",
    bg: "slate",
    skin: "light",
    hair: "black",
    hairStyle: "buzz",
    cloth: "hoodie",
    outfit: "hoodie",
  },
  "cas-tee": {
    id: "cas-tee",
    label: "Tee",
    category: "casual",
    kind: "human",
    bg: "lime",
    skin: "tan",
    hair: "brown",
    hairStyle: "curly",
    cloth: "leaf",
    outfit: "tee",
  },
  "cas-polo": {
    id: "cas-polo",
    label: "Polo",
    category: "casual",
    kind: "human",
    bg: "sky",
    skin: "fair",
    hair: "blonde",
    hairStyle: "short",
    cloth: "sky",
    outfit: "polo",
  },
  "cas-sweater": {
    id: "cas-sweater",
    label: "Sweater",
    category: "casual",
    kind: "human",
    bg: "rose",
    skin: "brown",
    hair: "darkBrown",
    hairStyle: "afro",
    cloth: "violet",
    outfit: "sweater",
    face: "blush",
  },
  "cas-teen": {
    id: "cas-teen",
    label: "Teen",
    category: "casual",
    kind: "human",
    bg: "cream",
    skin: "medium",
    hair: "black",
    hairStyle: "side",
    cloth: "amber",
    outfit: "hoodie",
    age: "youth",
    accessory: "cap",
  },

  // —— Technical ——
  "dev-01": {
    id: "dev-01",
    label: "Engineer",
    category: "technical",
    kind: "human",
    bg: "navy",
    skin: "light",
    hair: "black",
    hairStyle: "short",
    cloth: "hoodie",
    outfit: "hoodie",
    accessory: "glasses",
  },
  "dev-ops": {
    id: "dev-ops",
    label: "DevOps",
    category: "technical",
    kind: "human",
    bg: "slate",
    skin: "tan",
    hair: "brown",
    hairStyle: "buzz",
    cloth: "steel",
    outfit: "tee",
    accessory: "headset",
  },
  "dev-qa": {
    id: "dev-qa",
    label: "QA",
    category: "technical",
    kind: "human",
    bg: "mint",
    skin: "fair",
    hair: "blonde",
    hairStyle: "bob",
    cloth: "forest",
    outfit: "polo",
    accessory: "glasses",
  },
  "dev-data": {
    id: "dev-data",
    label: "Data",
    category: "technical",
    kind: "human",
    bg: "lavender",
    skin: "medium",
    hair: "darkBrown",
    hairStyle: "bun",
    cloth: "purple",
    outfit: "lab",
    accessory: "glasses",
  },
  "dev-sec": {
    id: "dev-sec",
    label: "Security",
    category: "technical",
    kind: "human",
    bg: "sand",
    skin: "deep",
    hair: "black",
    hairStyle: "short",
    cloth: "charcoal",
    outfit: "hoodie",
    face: "beard",
  },
  "dev-cloud": {
    id: "dev-cloud",
    label: "Cloud",
    category: "technical",
    kind: "human",
    bg: "ice",
    skin: "brown",
    hair: "black",
    hairStyle: "turban",
    cloth: "sky",
    outfit: "shirt",
  },

  // —— Creative ——
  "cre-ui": {
    id: "cre-ui",
    label: "UI Designer",
    category: "creative",
    kind: "human",
    bg: "blush",
    skin: "fair",
    hair: "pink",
    hairStyle: "bob",
    cloth: "pink",
    outfit: "tee",
    accessory: "glasses",
    face: "blush",
  },
  "cre-ux": {
    id: "cre-ux",
    label: "UX Designer",
    category: "creative",
    kind: "human",
    bg: "lilac",
    skin: "tan",
    hair: "purple",
    hairStyle: "curly",
    cloth: "indigo",
    outfit: "sweater",
  },
  "cre-product": {
    id: "cre-product",
    label: "Product",
    category: "creative",
    kind: "human",
    bg: "peach",
    skin: "medium",
    hair: "auburn",
    hairStyle: "ponytail",
    cloth: "orange",
    outfit: "blazer",
  },
  "cre-art": {
    id: "cre-art",
    label: "Illustrator",
    category: "creative",
    kind: "human",
    bg: "cream",
    skin: "light",
    hair: "blue",
    hairStyle: "short",
    cloth: "sky",
    outfit: "tee",
    accessory: "glasses",
  },

  // —— Students ——
  "stu-grad": {
    id: "stu-grad",
    label: "Graduate",
    category: "student",
    kind: "human",
    bg: "sand",
    skin: "tan",
    hair: "black",
    hairStyle: "short",
    cloth: "navy",
    outfit: "grad",
    accessory: "cap",
  },
  "stu-college": {
    id: "stu-college",
    label: "College",
    category: "student",
    kind: "human",
    bg: "ice",
    skin: "fair",
    hair: "brown",
    hairStyle: "long",
    cloth: "sky",
    outfit: "hoodie",
    accessory: "backpack",
    age: "youth",
  },
  "stu-school": {
    id: "stu-school",
    label: "School",
    category: "student",
    kind: "human",
    bg: "lime",
    skin: "medium",
    hair: "black",
    hairStyle: "short",
    cloth: "leaf",
    outfit: "tee",
    age: "youth",
    face: "blush",
  },

  // —— Generic ——
  "gen-male": {
    id: "gen-male",
    label: "User",
    category: "generic",
    kind: "human",
    bg: "slate",
    skin: "medium",
    hair: "brown",
    hairStyle: "short",
    cloth: "steel",
    outfit: "shirt",
  },
  "gen-female": {
    id: "gen-female",
    label: "User",
    category: "generic",
    kind: "human",
    bg: "blush",
    skin: "light",
    hair: "darkBrown",
    hairStyle: "bob",
    cloth: "magenta",
    outfit: "shirt",
  },
  "gen-neutral": {
    id: "gen-neutral",
    label: "User",
    category: "generic",
    kind: "human",
    bg: "lilac",
    skin: "tan",
    hair: "black",
    hairStyle: "buzz",
    cloth: "indigo",
    outfit: "tee",
  },
  placeholder: {
    id: "placeholder",
    label: "Anonymous",
    category: "generic",
    kind: "placeholder",
  },

  // —— Robots ——
  "robot-blue": {
    id: "robot-blue",
    label: "Robot Blue",
    category: "robot",
    kind: "robot",
    bg: "ice",
    robotColor: "#42A5F5",
  },
  "robot-purple": {
    id: "robot-purple",
    label: "Robot Purple",
    category: "robot",
    kind: "robot",
    bg: "lavender",
    robotColor: "#AB47BC",
  },
  "robot-green": {
    id: "robot-green",
    label: "Robot Green",
    category: "robot",
    kind: "robot",
    bg: "mint",
    robotColor: "#66BB6A",
  },
  "robot-gold": {
    id: "robot-gold",
    label: "Robot Gold",
    category: "robot",
    kind: "robot",
    bg: "cream",
    robotColor: "#FFA726",
  },

  // —— Mascots ——
  panda: { id: "panda", label: "Panda", category: "mascot", kind: "mascot", bg: "slate", mascot: "panda" },
  fox: { id: "fox", label: "Fox", category: "mascot", kind: "mascot", bg: "peach", mascot: "fox" },
  owl: { id: "owl", label: "Owl", category: "mascot", kind: "mascot", bg: "sand", mascot: "owl" },
  cat: { id: "cat", label: "Cat", category: "mascot", kind: "mascot", bg: "cream", mascot: "cat" },
  penguin: { id: "penguin", label: "Penguin", category: "mascot", kind: "mascot", bg: "ice", mascot: "penguin" },
  bear: { id: "bear", label: "Bear", category: "mascot", kind: "mascot", bg: "sand", mascot: "bear" },

  // —— Initials templates ——
  "init-a": {
    id: "init-a",
    label: "A",
    category: "initials",
    kind: "initials",
    initials: "A",
    gradientFrom: "#2563EB",
    gradientTo: "#7C3AED",
  },
  "init-r": {
    id: "init-r",
    label: "R",
    category: "initials",
    kind: "initials",
    initials: "R",
    gradientFrom: "#059669",
    gradientTo: "#0EA5E9",
  },
  "init-s": {
    id: "init-s",
    label: "S",
    category: "initials",
    kind: "initials",
    initials: "S",
    gradientFrom: "#DB2777",
    gradientTo: "#F59E0B",
  },
  "init-k": {
    id: "init-k",
    label: "K",
    category: "initials",
    kind: "initials",
    initials: "K",
    gradientFrom: "#4F46E5",
    gradientTo: "#06B6D4",
  },
  "init-m": {
    id: "init-m",
    label: "M",
    category: "initials",
    kind: "initials",
    initials: "M",
    gradientFrom: "#EA580C",
    gradientTo: "#E11D48",
  },
  "init-t": {
    id: "init-t",
    label: "T",
    category: "initials",
    kind: "initials",
    initials: "T",
    gradientFrom: "#0F766E",
    gradientTo: "#2563EB",
  },
  "init-p": {
    id: "init-p",
    label: "P",
    category: "initials",
    kind: "initials",
    initials: "P",
    gradientFrom: "#7C3AED",
    gradientTo: "#DB2777",
  },
  "init-v": {
    id: "init-v",
    label: "V",
    category: "initials",
    kind: "initials",
    initials: "V",
    gradientFrom: "#1D4ED8",
    gradientTo: "#16A34A",
  },
};

export const AVATAR_LIST = Object.values(AVATAR_MAP);

export const AVATAR_CATEGORIES: Array<{ id: AvatarCategory; label: string }> = [
  { id: "professional", label: "Professional" },
  { id: "casual", label: "Casual" },
  { id: "technical", label: "Technical" },
  { id: "creative", label: "Creative" },
  { id: "student", label: "Students" },
  { id: "man", label: "Men" },
  { id: "woman", label: "Women" },
  { id: "boy", label: "Boys" },
  { id: "girl", label: "Girls" },
  { id: "robot", label: "Robots" },
  { id: "mascot", label: "Mascots" },
  { id: "initials", label: "Initials" },
  { id: "generic", label: "Generic" },
];

export function resolveAvatarDefinition(id: string | null | undefined): AvatarDefinition | null {
  if (!id) return null;
  return AVATAR_MAP[id] ?? null;
}

export function isAvatarId(value: string | null | undefined): value is string {
  return !!value && value in AVATAR_MAP;
}

/** Build a dynamic initials avatar (not stored in registry). */
export function initialsAvatarDef(
  name: string,
  opts?: { from?: string; to?: string },
): AvatarDefinition {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  const letters =
    parts.length >= 2
      ? `${parts[0]![0] ?? ""}${parts[1]![0] ?? ""}`
      : (parts[0] ?? "?").slice(0, 2);
  return {
    id: `dyn-${letters.toLowerCase()}`,
    label: letters.toUpperCase() || "?",
    category: "initials",
    kind: "initials",
    initials: letters.toUpperCase() || "?",
    gradientFrom: opts?.from ?? "#2563EB",
    gradientTo: opts?.to ?? "#7C3AED",
  };
}
