/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TakeExamIdRouteImport } from './routes/take.$examId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBlueprintsRouteImport } from './routes/_authenticated/admin.blueprints'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminGamificationRouteImport } from './routes/_authenticated/admin.gamification'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin.organizations'
import { Route as AuthenticatedAdminPerformanceRouteImport } from './routes/_authenticated/admin.performance'
import { Route as AuthenticatedAdminPlayRouteImport } from './routes/_authenticated/admin.play'
import { Route as AuthenticatedAdminPoolsRouteImport } from './routes/_authenticated/admin.pools'
import { Route as AuthenticatedAdminSeriesRouteImport } from './routes/_authenticated/admin.series'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated/attempt.$attemptId'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated/play.index'
import { Route as AuthenticatedPlayArenaRouteImport } from './routes/_authenticated/play.arena'
import { Route as AuthenticatedPlayBattleRouteImport } from './routes/_authenticated/play.battle'
import { Route as AuthenticatedPlayEscapeRouteImport } from './routes/_authenticated/play.escape'
import { Route as AuthenticatedPlayFlashRouteImport } from './routes/_authenticated/play.flash'
import { Route as AuthenticatedPlayKnockoutRouteImport } from './routes/_authenticated/play.knockout'
import { Route as AuthenticatedPlayLeaderboardRouteImport } from './routes/_authenticated/play.leaderboard'
import { Route as AuthenticatedPlayTeamRouteImport } from './routes/_authenticated/play.team'
import { Route as AuthenticatedPlayTopicsRouteImport } from './routes/_authenticated/play.topics'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedAdminBlueprintsIndexRouteImport } from './routes/_authenticated/admin.blueprints.index'
import { Route as AuthenticatedAdminBlueprintsBlueprintIdRouteImport } from './routes/_authenticated/admin.blueprints.$blueprintId'
import { Route as AuthenticatedAdminBlueprintsNewRouteImport } from './routes/_authenticated/admin.blueprints.new'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin.exams.index'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'
import { Route as AuthenticatedAdminExamsNewRouteImport } from './routes/_authenticated/admin.exams.new'
import { Route as AuthenticatedAdminPlayIndexRouteImport } from './routes/_authenticated/admin.play.index'
import { Route as AuthenticatedAdminPlayEscapeRouteImport } from './routes/_authenticated/admin.play.escape'
import { Route as AuthenticatedAdminPlayKnockoutRouteImport } from './routes/_authenticated/admin.play.knockout'
import { Route as AuthenticatedAdminPlayLiveArenaRouteImport } from './routes/_authenticated/admin.play.live-arena'
import { Route as AuthenticatedAdminPoolsIndexRouteImport } from './routes/_authenticated/admin.pools.index'
import { Route as AuthenticatedAdminPoolsPoolIdRouteImport } from './routes/_authenticated/admin.pools.$poolId'
import { Route as AuthenticatedPlayArenaIndexRouteImport } from './routes/_authenticated/play.arena.index'
import { Route as AuthenticatedPlayArenaArenaIdRouteImport } from './routes/_authenticated/play.arena.$arenaId'
import { Route as AuthenticatedPlayEscapeScenarioIdRouteImport } from './routes/_authenticated/play.escape.$scenarioId'
import { Route as AuthenticatedPlayResultsSessionIdRouteImport } from './routes/_authenticated/play.results.$sessionId'
import { Route as AuthenticatedPlaySessionSessionIdRouteImport } from './routes/_authenticated/play.session.$sessionId'
import { Route as AuthenticatedPlayTournamentTournamentIdRouteImport } from './routes/_authenticated/play.tournament.$tournamentId'
import { Route as AuthenticatedAdminPlayModesKindRouteImport } from './routes/_authenticated/admin.play.modes.$kind'
import { Route as AuthenticatedAdminPlayArenaArenaIdRouteImport } from './routes/_authenticated/admin.play_.arena.$arenaId'
import { Route as AuthenticatedAdminPlayScoreboardArenaIdRouteImport } from './routes/_authenticated/admin.play_.scoreboard.$arenaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const TakeExamIdRoute = TakeExamIdRouteImport.update({
  id: '/take/$examId',
  path: '/take/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBlueprintsRoute =
  AuthenticatedAdminBlueprintsRouteImport.update({
    id: '/admin/blueprints',
    path: '/admin/blueprints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGamificationRoute =
  AuthenticatedAdminGamificationRouteImport.update({
    id: '/admin/gamification',
    path: '/admin/gamification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerformanceRoute =
  AuthenticatedAdminPerformanceRouteImport.update({
    id: '/admin/performance',
    path: '/admin/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlayRoute = AuthenticatedAdminPlayRouteImport.update({
  id: '/admin/play',
  path: '/admin/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPoolsRoute = AuthenticatedAdminPoolsRouteImport.update({
  id: '/admin/pools',
  path: '/admin/pools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSeriesRoute =
  AuthenticatedAdminSeriesRouteImport.update({
    id: '/admin/series',
    path: '/admin/series',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayArenaRoute = AuthenticatedPlayArenaRouteImport.update({
  id: '/play/arena',
  path: '/play/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayBattleRoute = AuthenticatedPlayBattleRouteImport.update({
  id: '/play/battle',
  path: '/play/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayEscapeRoute = AuthenticatedPlayEscapeRouteImport.update({
  id: '/play/escape',
  path: '/play/escape',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayFlashRoute = AuthenticatedPlayFlashRouteImport.update({
  id: '/play/flash',
  path: '/play/flash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayKnockoutRoute =
  AuthenticatedPlayKnockoutRouteImport.update({
    id: '/play/knockout',
    path: '/play/knockout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayLeaderboardRoute =
  AuthenticatedPlayLeaderboardRouteImport.update({
    id: '/play/leaderboard',
    path: '/play/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayTeamRoute = AuthenticatedPlayTeamRouteImport.update({
  id: '/play/team',
  path: '/play/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayTopicsRoute = AuthenticatedPlayTopicsRouteImport.update({
  id: '/play/topics',
  path: '/play/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlueprintsIndexRoute =
  AuthenticatedAdminBlueprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlueprintsRoute,
  } as any)
const AuthenticatedAdminBlueprintsBlueprintIdRoute =
  AuthenticatedAdminBlueprintsBlueprintIdRouteImport.update({
    id: '/$blueprintId',
    path: '/$blueprintId',
    getParentRoute: () => AuthenticatedAdminBlueprintsRoute,
  } as any)
const AuthenticatedAdminBlueprintsNewRoute =
  AuthenticatedAdminBlueprintsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBlueprintsRoute,
  } as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminExamsNewRoute =
  AuthenticatedAdminExamsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminPlayIndexRoute =
  AuthenticatedAdminPlayIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPlayRoute,
  } as any)
const AuthenticatedAdminPlayEscapeRoute =
  AuthenticatedAdminPlayEscapeRouteImport.update({
    id: '/escape',
    path: '/escape',
    getParentRoute: () => AuthenticatedAdminPlayRoute,
  } as any)
const AuthenticatedAdminPlayKnockoutRoute =
  AuthenticatedAdminPlayKnockoutRouteImport.update({
    id: '/knockout',
    path: '/knockout',
    getParentRoute: () => AuthenticatedAdminPlayRoute,
  } as any)
const AuthenticatedAdminPlayLiveArenaRoute =
  AuthenticatedAdminPlayLiveArenaRouteImport.update({
    id: '/live-arena',
    path: '/live-arena',
    getParentRoute: () => AuthenticatedAdminPlayRoute,
  } as any)
const AuthenticatedAdminPoolsIndexRoute =
  AuthenticatedAdminPoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPoolsRoute,
  } as any)
const AuthenticatedAdminPoolsPoolIdRoute =
  AuthenticatedAdminPoolsPoolIdRouteImport.update({
    id: '/$poolId',
    path: '/$poolId',
    getParentRoute: () => AuthenticatedAdminPoolsRoute,
  } as any)
const AuthenticatedPlayArenaIndexRoute =
  AuthenticatedPlayArenaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlayArenaRoute,
  } as any)
const AuthenticatedPlayArenaArenaIdRoute =
  AuthenticatedPlayArenaArenaIdRouteImport.update({
    id: '/$arenaId',
    path: '/$arenaId',
    getParentRoute: () => AuthenticatedPlayArenaRoute,
  } as any)
const AuthenticatedPlayEscapeScenarioIdRoute =
  AuthenticatedPlayEscapeScenarioIdRouteImport.update({
    id: '/$scenarioId',
    path: '/$scenarioId',
    getParentRoute: () => AuthenticatedPlayEscapeRoute,
  } as any)
const AuthenticatedPlayResultsSessionIdRoute =
  AuthenticatedPlayResultsSessionIdRouteImport.update({
    id: '/play/results/$sessionId',
    path: '/play/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaySessionSessionIdRoute =
  AuthenticatedPlaySessionSessionIdRouteImport.update({
    id: '/play/session/$sessionId',
    path: '/play/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayTournamentTournamentIdRoute =
  AuthenticatedPlayTournamentTournamentIdRouteImport.update({
    id: '/play/tournament/$tournamentId',
    path: '/play/tournament/$tournamentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlayModesKindRoute =
  AuthenticatedAdminPlayModesKindRouteImport.update({
    id: '/modes/$kind',
    path: '/modes/$kind',
    getParentRoute: () => AuthenticatedAdminPlayRoute,
  } as any)
const AuthenticatedAdminPlayArenaArenaIdRoute =
  AuthenticatedAdminPlayArenaArenaIdRouteImport.update({
    id: '/admin/play_/arena/$arenaId',
    path: '/admin/play/arena/$arenaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlayScoreboardArenaIdRoute =
  AuthenticatedAdminPlayScoreboardArenaIdRouteImport.update({
    id: '/admin/play_/scoreboard/$arenaId',
    path: '/admin/play/scoreboard/$arenaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/admin/blueprints': typeof AuthenticatedAdminBlueprintsRouteWithChildren
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/play': typeof AuthenticatedAdminPlayRouteWithChildren
  '/admin/pools': typeof AuthenticatedAdminPoolsRouteWithChildren
  '/admin/series': typeof AuthenticatedAdminSeriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/play/arena': typeof AuthenticatedPlayArenaRouteWithChildren
  '/play/battle': typeof AuthenticatedPlayBattleRoute
  '/play/escape': typeof AuthenticatedPlayEscapeRouteWithChildren
  '/play/flash': typeof AuthenticatedPlayFlashRoute
  '/play/knockout': typeof AuthenticatedPlayKnockoutRoute
  '/play/leaderboard': typeof AuthenticatedPlayLeaderboardRoute
  '/play/team': typeof AuthenticatedPlayTeamRoute
  '/play/topics': typeof AuthenticatedPlayTopicsRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
  '/admin/blueprints/$blueprintId': typeof AuthenticatedAdminBlueprintsBlueprintIdRoute
  '/admin/blueprints/new': typeof AuthenticatedAdminBlueprintsNewRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/play/escape': typeof AuthenticatedAdminPlayEscapeRoute
  '/admin/play/knockout': typeof AuthenticatedAdminPlayKnockoutRoute
  '/admin/play/live-arena': typeof AuthenticatedAdminPlayLiveArenaRoute
  '/admin/pools/$poolId': typeof AuthenticatedAdminPoolsPoolIdRoute
  '/play/arena/$arenaId': typeof AuthenticatedPlayArenaArenaIdRoute
  '/play/escape/$scenarioId': typeof AuthenticatedPlayEscapeScenarioIdRoute
  '/play/results/$sessionId': typeof AuthenticatedPlayResultsSessionIdRoute
  '/play/session/$sessionId': typeof AuthenticatedPlaySessionSessionIdRoute
  '/play/tournament/$tournamentId': typeof AuthenticatedPlayTournamentTournamentIdRoute
  '/admin/blueprints/': typeof AuthenticatedAdminBlueprintsIndexRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/play/': typeof AuthenticatedAdminPlayIndexRoute
  '/admin/pools/': typeof AuthenticatedAdminPoolsIndexRoute
  '/play/arena/': typeof AuthenticatedPlayArenaIndexRoute
  '/admin/play/modes/$kind': typeof AuthenticatedAdminPlayModesKindRoute
  '/admin/play/arena/$arenaId': typeof AuthenticatedAdminPlayArenaArenaIdRoute
  '/admin/play/scoreboard/$arenaId': typeof AuthenticatedAdminPlayScoreboardArenaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/series': typeof AuthenticatedAdminSeriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/play/battle': typeof AuthenticatedPlayBattleRoute
  '/play/escape': typeof AuthenticatedPlayEscapeRouteWithChildren
  '/play/flash': typeof AuthenticatedPlayFlashRoute
  '/play/knockout': typeof AuthenticatedPlayKnockoutRoute
  '/play/leaderboard': typeof AuthenticatedPlayLeaderboardRoute
  '/play/team': typeof AuthenticatedPlayTeamRoute
  '/play/topics': typeof AuthenticatedPlayTopicsRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/play': typeof AuthenticatedPlayIndexRoute
  '/admin/blueprints/$blueprintId': typeof AuthenticatedAdminBlueprintsBlueprintIdRoute
  '/admin/blueprints/new': typeof AuthenticatedAdminBlueprintsNewRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/play/escape': typeof AuthenticatedAdminPlayEscapeRoute
  '/admin/play/knockout': typeof AuthenticatedAdminPlayKnockoutRoute
  '/admin/play/live-arena': typeof AuthenticatedAdminPlayLiveArenaRoute
  '/admin/pools/$poolId': typeof AuthenticatedAdminPoolsPoolIdRoute
  '/play/arena/$arenaId': typeof AuthenticatedPlayArenaArenaIdRoute
  '/play/escape/$scenarioId': typeof AuthenticatedPlayEscapeScenarioIdRoute
  '/play/results/$sessionId': typeof AuthenticatedPlayResultsSessionIdRoute
  '/play/session/$sessionId': typeof AuthenticatedPlaySessionSessionIdRoute
  '/play/tournament/$tournamentId': typeof AuthenticatedPlayTournamentTournamentIdRoute
  '/admin/blueprints': typeof AuthenticatedAdminBlueprintsIndexRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/play': typeof AuthenticatedAdminPlayIndexRoute
  '/admin/pools': typeof AuthenticatedAdminPoolsIndexRoute
  '/play/arena': typeof AuthenticatedPlayArenaIndexRoute
  '/admin/play/modes/$kind': typeof AuthenticatedAdminPlayModesKindRoute
  '/admin/play/arena/$arenaId': typeof AuthenticatedAdminPlayArenaArenaIdRoute
  '/admin/play/scoreboard/$arenaId': typeof AuthenticatedAdminPlayScoreboardArenaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/_authenticated/admin/blueprints': typeof AuthenticatedAdminBlueprintsRouteWithChildren
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/_authenticated/admin/play': typeof AuthenticatedAdminPlayRouteWithChildren
  '/_authenticated/admin/pools': typeof AuthenticatedAdminPoolsRouteWithChildren
  '/_authenticated/admin/series': typeof AuthenticatedAdminSeriesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/_authenticated/play/arena': typeof AuthenticatedPlayArenaRouteWithChildren
  '/_authenticated/play/battle': typeof AuthenticatedPlayBattleRoute
  '/_authenticated/play/escape': typeof AuthenticatedPlayEscapeRouteWithChildren
  '/_authenticated/play/flash': typeof AuthenticatedPlayFlashRoute
  '/_authenticated/play/knockout': typeof AuthenticatedPlayKnockoutRoute
  '/_authenticated/play/leaderboard': typeof AuthenticatedPlayLeaderboardRoute
  '/_authenticated/play/team': typeof AuthenticatedPlayTeamRoute
  '/_authenticated/play/topics': typeof AuthenticatedPlayTopicsRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
  '/_authenticated/admin/blueprints/$blueprintId': typeof AuthenticatedAdminBlueprintsBlueprintIdRoute
  '/_authenticated/admin/blueprints/new': typeof AuthenticatedAdminBlueprintsNewRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/_authenticated/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/_authenticated/admin/play/escape': typeof AuthenticatedAdminPlayEscapeRoute
  '/_authenticated/admin/play/knockout': typeof AuthenticatedAdminPlayKnockoutRoute
  '/_authenticated/admin/play/live-arena': typeof AuthenticatedAdminPlayLiveArenaRoute
  '/_authenticated/admin/pools/$poolId': typeof AuthenticatedAdminPoolsPoolIdRoute
  '/_authenticated/play/arena/$arenaId': typeof AuthenticatedPlayArenaArenaIdRoute
  '/_authenticated/play/escape/$scenarioId': typeof AuthenticatedPlayEscapeScenarioIdRoute
  '/_authenticated/play/results/$sessionId': typeof AuthenticatedPlayResultsSessionIdRoute
  '/_authenticated/play/session/$sessionId': typeof AuthenticatedPlaySessionSessionIdRoute
  '/_authenticated/play/tournament/$tournamentId': typeof AuthenticatedPlayTournamentTournamentIdRoute
  '/_authenticated/admin/blueprints/': typeof AuthenticatedAdminBlueprintsIndexRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/_authenticated/admin/play/': typeof AuthenticatedAdminPlayIndexRoute
  '/_authenticated/admin/pools/': typeof AuthenticatedAdminPoolsIndexRoute
  '/_authenticated/play/arena/': typeof AuthenticatedPlayArenaIndexRoute
  '/_authenticated/admin/play/modes/$kind': typeof AuthenticatedAdminPlayModesKindRoute
  '/_authenticated/admin/play_/arena/$arenaId': typeof AuthenticatedAdminPlayArenaArenaIdRoute
  '/_authenticated/admin/play_/scoreboard/$arenaId': typeof AuthenticatedAdminPlayScoreboardArenaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/achievements'
    | '/dashboard'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/auth/callback'
    | '/take/$examId'
    | '/admin/blueprints'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/gamification'
    | '/admin/organizations'
    | '/admin/performance'
    | '/admin/play'
    | '/admin/pools'
    | '/admin/series'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/exams/$examId'
    | '/play/arena'
    | '/play/battle'
    | '/play/escape'
    | '/play/flash'
    | '/play/knockout'
    | '/play/leaderboard'
    | '/play/team'
    | '/play/topics'
    | '/results/$attemptId'
    | '/admin/'
    | '/exams/'
    | '/play/'
    | '/admin/blueprints/$blueprintId'
    | '/admin/blueprints/new'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/play/escape'
    | '/admin/play/knockout'
    | '/admin/play/live-arena'
    | '/admin/pools/$poolId'
    | '/play/arena/$arenaId'
    | '/play/escape/$scenarioId'
    | '/play/results/$sessionId'
    | '/play/session/$sessionId'
    | '/play/tournament/$tournamentId'
    | '/admin/blueprints/'
    | '/admin/exams/'
    | '/admin/play/'
    | '/admin/pools/'
    | '/play/arena/'
    | '/admin/play/modes/$kind'
    | '/admin/play/arena/$arenaId'
    | '/admin/play/scoreboard/$arenaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/achievements'
    | '/dashboard'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/auth/callback'
    | '/take/$examId'
    | '/admin/courses'
    | '/admin/gamification'
    | '/admin/organizations'
    | '/admin/performance'
    | '/admin/series'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/exams/$examId'
    | '/play/battle'
    | '/play/escape'
    | '/play/flash'
    | '/play/knockout'
    | '/play/leaderboard'
    | '/play/team'
    | '/play/topics'
    | '/results/$attemptId'
    | '/admin'
    | '/exams'
    | '/play'
    | '/admin/blueprints/$blueprintId'
    | '/admin/blueprints/new'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/play/escape'
    | '/admin/play/knockout'
    | '/admin/play/live-arena'
    | '/admin/pools/$poolId'
    | '/play/arena/$arenaId'
    | '/play/escape/$scenarioId'
    | '/play/results/$sessionId'
    | '/play/session/$sessionId'
    | '/play/tournament/$tournamentId'
    | '/admin/blueprints'
    | '/admin/exams'
    | '/admin/play'
    | '/admin/pools'
    | '/play/arena'
    | '/admin/play/modes/$kind'
    | '/admin/play/arena/$arenaId'
    | '/admin/play/scoreboard/$arenaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/achievements'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/auth/callback'
    | '/take/$examId'
    | '/_authenticated/admin/blueprints'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/gamification'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/performance'
    | '/_authenticated/admin/play'
    | '/_authenticated/admin/pools'
    | '/_authenticated/admin/series'
    | '/_authenticated/admin/users'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/play/arena'
    | '/_authenticated/play/battle'
    | '/_authenticated/play/escape'
    | '/_authenticated/play/flash'
    | '/_authenticated/play/knockout'
    | '/_authenticated/play/leaderboard'
    | '/_authenticated/play/team'
    | '/_authenticated/play/topics'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/admin/'
    | '/_authenticated/exams/'
    | '/_authenticated/play/'
    | '/_authenticated/admin/blueprints/$blueprintId'
    | '/_authenticated/admin/blueprints/new'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/exams/new'
    | '/_authenticated/admin/play/escape'
    | '/_authenticated/admin/play/knockout'
    | '/_authenticated/admin/play/live-arena'
    | '/_authenticated/admin/pools/$poolId'
    | '/_authenticated/play/arena/$arenaId'
    | '/_authenticated/play/escape/$scenarioId'
    | '/_authenticated/play/results/$sessionId'
    | '/_authenticated/play/session/$sessionId'
    | '/_authenticated/play/tournament/$tournamentId'
    | '/_authenticated/admin/blueprints/'
    | '/_authenticated/admin/exams/'
    | '/_authenticated/admin/play/'
    | '/_authenticated/admin/pools/'
    | '/_authenticated/play/arena/'
    | '/_authenticated/admin/play/modes/$kind'
    | '/_authenticated/admin/play_/arena/$arenaId'
    | '/_authenticated/admin/play_/scoreboard/$arenaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TakeExamIdRoute: typeof TakeExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/take/$examId': {
      id: '/take/$examId'
      path: '/take/$examId'
      fullPath: '/take/$examId'
      preLoaderRoute: typeof TakeExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blueprints': {
      id: '/_authenticated/admin/blueprints'
      path: '/admin/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AuthenticatedAdminBlueprintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gamification': {
      id: '/_authenticated/admin/gamification'
      path: '/admin/gamification'
      fullPath: '/admin/gamification'
      preLoaderRoute: typeof AuthenticatedAdminGamificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/performance': {
      id: '/_authenticated/admin/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/play': {
      id: '/_authenticated/admin/play'
      path: '/admin/play'
      fullPath: '/admin/play'
      preLoaderRoute: typeof AuthenticatedAdminPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pools': {
      id: '/_authenticated/admin/pools'
      path: '/admin/pools'
      fullPath: '/admin/pools'
      preLoaderRoute: typeof AuthenticatedAdminPoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/series': {
      id: '/_authenticated/admin/series'
      path: '/admin/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AuthenticatedAdminSeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/arena': {
      id: '/_authenticated/play/arena'
      path: '/play/arena'
      fullPath: '/play/arena'
      preLoaderRoute: typeof AuthenticatedPlayArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/battle': {
      id: '/_authenticated/play/battle'
      path: '/play/battle'
      fullPath: '/play/battle'
      preLoaderRoute: typeof AuthenticatedPlayBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/escape': {
      id: '/_authenticated/play/escape'
      path: '/play/escape'
      fullPath: '/play/escape'
      preLoaderRoute: typeof AuthenticatedPlayEscapeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/flash': {
      id: '/_authenticated/play/flash'
      path: '/play/flash'
      fullPath: '/play/flash'
      preLoaderRoute: typeof AuthenticatedPlayFlashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/knockout': {
      id: '/_authenticated/play/knockout'
      path: '/play/knockout'
      fullPath: '/play/knockout'
      preLoaderRoute: typeof AuthenticatedPlayKnockoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/leaderboard': {
      id: '/_authenticated/play/leaderboard'
      path: '/play/leaderboard'
      fullPath: '/play/leaderboard'
      preLoaderRoute: typeof AuthenticatedPlayLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/team': {
      id: '/_authenticated/play/team'
      path: '/play/team'
      fullPath: '/play/team'
      preLoaderRoute: typeof AuthenticatedPlayTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/topics': {
      id: '/_authenticated/play/topics'
      path: '/play/topics'
      fullPath: '/play/topics'
      preLoaderRoute: typeof AuthenticatedPlayTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blueprints/': {
      id: '/_authenticated/admin/blueprints/'
      path: '/'
      fullPath: '/admin/blueprints/'
      preLoaderRoute: typeof AuthenticatedAdminBlueprintsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlueprintsRoute
    }
    '/_authenticated/admin/blueprints/$blueprintId': {
      id: '/_authenticated/admin/blueprints/$blueprintId'
      path: '/$blueprintId'
      fullPath: '/admin/blueprints/$blueprintId'
      preLoaderRoute: typeof AuthenticatedAdminBlueprintsBlueprintIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlueprintsRoute
    }
    '/_authenticated/admin/blueprints/new': {
      id: '/_authenticated/admin/blueprints/new'
      path: '/new'
      fullPath: '/admin/blueprints/new'
      preLoaderRoute: typeof AuthenticatedAdminBlueprintsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBlueprintsRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/exams/new': {
      id: '/_authenticated/admin/exams/new'
      path: '/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AuthenticatedAdminExamsNewRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/play/': {
      id: '/_authenticated/admin/play/'
      path: '/'
      fullPath: '/admin/play/'
      preLoaderRoute: typeof AuthenticatedAdminPlayIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPlayRoute
    }
    '/_authenticated/admin/play/escape': {
      id: '/_authenticated/admin/play/escape'
      path: '/escape'
      fullPath: '/admin/play/escape'
      preLoaderRoute: typeof AuthenticatedAdminPlayEscapeRouteImport
      parentRoute: typeof AuthenticatedAdminPlayRoute
    }
    '/_authenticated/admin/play/knockout': {
      id: '/_authenticated/admin/play/knockout'
      path: '/knockout'
      fullPath: '/admin/play/knockout'
      preLoaderRoute: typeof AuthenticatedAdminPlayKnockoutRouteImport
      parentRoute: typeof AuthenticatedAdminPlayRoute
    }
    '/_authenticated/admin/play/live-arena': {
      id: '/_authenticated/admin/play/live-arena'
      path: '/live-arena'
      fullPath: '/admin/play/live-arena'
      preLoaderRoute: typeof AuthenticatedAdminPlayLiveArenaRouteImport
      parentRoute: typeof AuthenticatedAdminPlayRoute
    }
    '/_authenticated/admin/pools/': {
      id: '/_authenticated/admin/pools/'
      path: '/'
      fullPath: '/admin/pools/'
      preLoaderRoute: typeof AuthenticatedAdminPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPoolsRoute
    }
    '/_authenticated/admin/pools/$poolId': {
      id: '/_authenticated/admin/pools/$poolId'
      path: '/$poolId'
      fullPath: '/admin/pools/$poolId'
      preLoaderRoute: typeof AuthenticatedAdminPoolsPoolIdRouteImport
      parentRoute: typeof AuthenticatedAdminPoolsRoute
    }
    '/_authenticated/play/arena/': {
      id: '/_authenticated/play/arena/'
      path: '/'
      fullPath: '/play/arena/'
      preLoaderRoute: typeof AuthenticatedPlayArenaIndexRouteImport
      parentRoute: typeof AuthenticatedPlayArenaRoute
    }
    '/_authenticated/play/arena/$arenaId': {
      id: '/_authenticated/play/arena/$arenaId'
      path: '/$arenaId'
      fullPath: '/play/arena/$arenaId'
      preLoaderRoute: typeof AuthenticatedPlayArenaArenaIdRouteImport
      parentRoute: typeof AuthenticatedPlayArenaRoute
    }
    '/_authenticated/play/escape/$scenarioId': {
      id: '/_authenticated/play/escape/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/play/escape/$scenarioId'
      preLoaderRoute: typeof AuthenticatedPlayEscapeScenarioIdRouteImport
      parentRoute: typeof AuthenticatedPlayEscapeRoute
    }
    '/_authenticated/play/results/$sessionId': {
      id: '/_authenticated/play/results/$sessionId'
      path: '/play/results/$sessionId'
      fullPath: '/play/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlayResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/session/$sessionId': {
      id: '/_authenticated/play/session/$sessionId'
      path: '/play/session/$sessionId'
      fullPath: '/play/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlaySessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/tournament/$tournamentId': {
      id: '/_authenticated/play/tournament/$tournamentId'
      path: '/play/tournament/$tournamentId'
      fullPath: '/play/tournament/$tournamentId'
      preLoaderRoute: typeof AuthenticatedPlayTournamentTournamentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/play/modes/$kind': {
      id: '/_authenticated/admin/play/modes/$kind'
      path: '/modes/$kind'
      fullPath: '/admin/play/modes/$kind'
      preLoaderRoute: typeof AuthenticatedAdminPlayModesKindRouteImport
      parentRoute: typeof AuthenticatedAdminPlayRoute
    }
    '/_authenticated/admin/play_/arena/$arenaId': {
      id: '/_authenticated/admin/play_/arena/$arenaId'
      path: '/admin/play/arena/$arenaId'
      fullPath: '/admin/play/arena/$arenaId'
      preLoaderRoute: typeof AuthenticatedAdminPlayArenaArenaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/play_/scoreboard/$arenaId': {
      id: '/_authenticated/admin/play_/scoreboard/$arenaId'
      path: '/admin/play/scoreboard/$arenaId'
      fullPath: '/admin/play/scoreboard/$arenaId'
      preLoaderRoute: typeof AuthenticatedAdminPlayScoreboardArenaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminBlueprintsRouteChildren {
  AuthenticatedAdminBlueprintsBlueprintIdRoute: typeof AuthenticatedAdminBlueprintsBlueprintIdRoute
  AuthenticatedAdminBlueprintsNewRoute: typeof AuthenticatedAdminBlueprintsNewRoute
  AuthenticatedAdminBlueprintsIndexRoute: typeof AuthenticatedAdminBlueprintsIndexRoute
}

const AuthenticatedAdminBlueprintsRouteChildren: AuthenticatedAdminBlueprintsRouteChildren =
  {
    AuthenticatedAdminBlueprintsBlueprintIdRoute:
      AuthenticatedAdminBlueprintsBlueprintIdRoute,
    AuthenticatedAdminBlueprintsNewRoute: AuthenticatedAdminBlueprintsNewRoute,
    AuthenticatedAdminBlueprintsIndexRoute:
      AuthenticatedAdminBlueprintsIndexRoute,
  }

const AuthenticatedAdminBlueprintsRouteWithChildren =
  AuthenticatedAdminBlueprintsRoute._addFileChildren(
    AuthenticatedAdminBlueprintsRouteChildren,
  )

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRoute
  AuthenticatedAdminExamsNewRoute: typeof AuthenticatedAdminExamsNewRoute
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsExamIdRoute: AuthenticatedAdminExamsExamIdRoute,
    AuthenticatedAdminExamsNewRoute: AuthenticatedAdminExamsNewRoute,
    AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminPlayRouteChildren {
  AuthenticatedAdminPlayEscapeRoute: typeof AuthenticatedAdminPlayEscapeRoute
  AuthenticatedAdminPlayKnockoutRoute: typeof AuthenticatedAdminPlayKnockoutRoute
  AuthenticatedAdminPlayLiveArenaRoute: typeof AuthenticatedAdminPlayLiveArenaRoute
  AuthenticatedAdminPlayIndexRoute: typeof AuthenticatedAdminPlayIndexRoute
  AuthenticatedAdminPlayModesKindRoute: typeof AuthenticatedAdminPlayModesKindRoute
}

const AuthenticatedAdminPlayRouteChildren: AuthenticatedAdminPlayRouteChildren =
  {
    AuthenticatedAdminPlayEscapeRoute: AuthenticatedAdminPlayEscapeRoute,
    AuthenticatedAdminPlayKnockoutRoute: AuthenticatedAdminPlayKnockoutRoute,
    AuthenticatedAdminPlayLiveArenaRoute: AuthenticatedAdminPlayLiveArenaRoute,
    AuthenticatedAdminPlayIndexRoute: AuthenticatedAdminPlayIndexRoute,
    AuthenticatedAdminPlayModesKindRoute: AuthenticatedAdminPlayModesKindRoute,
  }

const AuthenticatedAdminPlayRouteWithChildren =
  AuthenticatedAdminPlayRoute._addFileChildren(
    AuthenticatedAdminPlayRouteChildren,
  )

interface AuthenticatedAdminPoolsRouteChildren {
  AuthenticatedAdminPoolsPoolIdRoute: typeof AuthenticatedAdminPoolsPoolIdRoute
  AuthenticatedAdminPoolsIndexRoute: typeof AuthenticatedAdminPoolsIndexRoute
}

const AuthenticatedAdminPoolsRouteChildren: AuthenticatedAdminPoolsRouteChildren =
  {
    AuthenticatedAdminPoolsPoolIdRoute: AuthenticatedAdminPoolsPoolIdRoute,
    AuthenticatedAdminPoolsIndexRoute: AuthenticatedAdminPoolsIndexRoute,
  }

const AuthenticatedAdminPoolsRouteWithChildren =
  AuthenticatedAdminPoolsRoute._addFileChildren(
    AuthenticatedAdminPoolsRouteChildren,
  )

interface AuthenticatedPlayArenaRouteChildren {
  AuthenticatedPlayArenaArenaIdRoute: typeof AuthenticatedPlayArenaArenaIdRoute
  AuthenticatedPlayArenaIndexRoute: typeof AuthenticatedPlayArenaIndexRoute
}

const AuthenticatedPlayArenaRouteChildren: AuthenticatedPlayArenaRouteChildren =
  {
    AuthenticatedPlayArenaArenaIdRoute: AuthenticatedPlayArenaArenaIdRoute,
    AuthenticatedPlayArenaIndexRoute: AuthenticatedPlayArenaIndexRoute,
  }

const AuthenticatedPlayArenaRouteWithChildren =
  AuthenticatedPlayArenaRoute._addFileChildren(
    AuthenticatedPlayArenaRouteChildren,
  )

interface AuthenticatedPlayEscapeRouteChildren {
  AuthenticatedPlayEscapeScenarioIdRoute: typeof AuthenticatedPlayEscapeScenarioIdRoute
}

const AuthenticatedPlayEscapeRouteChildren: AuthenticatedPlayEscapeRouteChildren =
  {
    AuthenticatedPlayEscapeScenarioIdRoute:
      AuthenticatedPlayEscapeScenarioIdRoute,
  }

const AuthenticatedPlayEscapeRouteWithChildren =
  AuthenticatedPlayEscapeRoute._addFileChildren(
    AuthenticatedPlayEscapeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedAdminBlueprintsRoute: typeof AuthenticatedAdminBlueprintsRouteWithChildren
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminGamificationRoute: typeof AuthenticatedAdminGamificationRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminPerformanceRoute: typeof AuthenticatedAdminPerformanceRoute
  AuthenticatedAdminPlayRoute: typeof AuthenticatedAdminPlayRouteWithChildren
  AuthenticatedAdminPoolsRoute: typeof AuthenticatedAdminPoolsRouteWithChildren
  AuthenticatedAdminSeriesRoute: typeof AuthenticatedAdminSeriesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRoute
  AuthenticatedPlayArenaRoute: typeof AuthenticatedPlayArenaRouteWithChildren
  AuthenticatedPlayBattleRoute: typeof AuthenticatedPlayBattleRoute
  AuthenticatedPlayEscapeRoute: typeof AuthenticatedPlayEscapeRouteWithChildren
  AuthenticatedPlayFlashRoute: typeof AuthenticatedPlayFlashRoute
  AuthenticatedPlayKnockoutRoute: typeof AuthenticatedPlayKnockoutRoute
  AuthenticatedPlayLeaderboardRoute: typeof AuthenticatedPlayLeaderboardRoute
  AuthenticatedPlayTeamRoute: typeof AuthenticatedPlayTeamRoute
  AuthenticatedPlayTopicsRoute: typeof AuthenticatedPlayTopicsRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
  AuthenticatedPlayResultsSessionIdRoute: typeof AuthenticatedPlayResultsSessionIdRoute
  AuthenticatedPlaySessionSessionIdRoute: typeof AuthenticatedPlaySessionSessionIdRoute
  AuthenticatedPlayTournamentTournamentIdRoute: typeof AuthenticatedPlayTournamentTournamentIdRoute
  AuthenticatedAdminPlayArenaArenaIdRoute: typeof AuthenticatedAdminPlayArenaArenaIdRoute
  AuthenticatedAdminPlayScoreboardArenaIdRoute: typeof AuthenticatedAdminPlayScoreboardArenaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedAdminBlueprintsRoute:
    AuthenticatedAdminBlueprintsRouteWithChildren,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminGamificationRoute: AuthenticatedAdminGamificationRoute,
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminPerformanceRoute: AuthenticatedAdminPerformanceRoute,
  AuthenticatedAdminPlayRoute: AuthenticatedAdminPlayRouteWithChildren,
  AuthenticatedAdminPoolsRoute: AuthenticatedAdminPoolsRouteWithChildren,
  AuthenticatedAdminSeriesRoute: AuthenticatedAdminSeriesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRoute,
  AuthenticatedPlayArenaRoute: AuthenticatedPlayArenaRouteWithChildren,
  AuthenticatedPlayBattleRoute: AuthenticatedPlayBattleRoute,
  AuthenticatedPlayEscapeRoute: AuthenticatedPlayEscapeRouteWithChildren,
  AuthenticatedPlayFlashRoute: AuthenticatedPlayFlashRoute,
  AuthenticatedPlayKnockoutRoute: AuthenticatedPlayKnockoutRoute,
  AuthenticatedPlayLeaderboardRoute: AuthenticatedPlayLeaderboardRoute,
  AuthenticatedPlayTeamRoute: AuthenticatedPlayTeamRoute,
  AuthenticatedPlayTopicsRoute: AuthenticatedPlayTopicsRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
  AuthenticatedPlayResultsSessionIdRoute:
    AuthenticatedPlayResultsSessionIdRoute,
  AuthenticatedPlaySessionSessionIdRoute:
    AuthenticatedPlaySessionSessionIdRoute,
  AuthenticatedPlayTournamentTournamentIdRoute:
    AuthenticatedPlayTournamentTournamentIdRoute,
  AuthenticatedAdminPlayArenaArenaIdRoute:
    AuthenticatedAdminPlayArenaArenaIdRoute,
  AuthenticatedAdminPlayScoreboardArenaIdRoute:
    AuthenticatedAdminPlayScoreboardArenaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TakeExamIdRoute: TakeExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
